### ISSUE TITLE
migration in DBS3 is automatically retried 3 times

### ISSUE THREAD

**Issue by belforte** [dmwm/CRAB2#1009]
it is not enough state=3 to say that it failed, need to check retry_count

**Comment by fanzago** [comment]
Stefano,  does it mean to check if 3 attempts have been done?

**Comment by belforte** [comment]
yes. terminal state is:
state=2 OR (state=3 AND retry_count=3)
any other state can still change

**Comment by belforte** [comment]
I have discussed with manuel addition of a 4th state, to make things clear
