### ISSUE TITLE
when reading DBS3 make sure files are valid

### ISSUE THREAD

**Issue by belforte** [dmwm/CRAB2#1036]
see:
https://hypernews.cern.ch/HyperNews/CMS/get/crabFeedback/7269/1/1/1/2.html

**Comment by yuyiguo** [comment]
DBS3 by default is return only valid dataset. The the DBS2 status is now called dataset_access_type in DBS3. The dataset access types are: valid, invalid, production ....
Please ignore the is_dataset_valid flag. It is set true to all datasets.

**Comment by belforte** [comment]
yes, listDatastes returns only valid datasets, but listFiles returns all files in a dataset 
including invalid ones.

On 02/28/2014 03:11 PM, Yuyi Guo wrote:

> DBS3 by default is return only valid dataset. The the DBS2 status is now called dataset_access_type
> in DBS3. The dataset access types are: valid, invalid, production ....
> Please ignore the is_dataset_valid flag. It is set true to all datasets.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dmwm/CRAB2/issues/1036#issuecomment-36353552.

## 

Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by yuyiguo** [comment]
listFiles requires  a dataset , a block or a lfn, so it lists what is required. We assume that when these names are given, one really want to know what inside is no mater it is valid or invalid.

**Comment by belforte** [comment]
sure. I am not complaining. We agree. I only say that in Crab2/3 we need to make sure we only use 
valid files. In the end we need a list of LFN's to give to cmsRun for reading.
