### ISSUE TITLE
Resubmitting with PBSv2 plugin is bad to stdout

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/CRAB2#1061]
I have a logic error where the "new" stdout is written to the Submission_1/ directory, leaving nothing left.

**Comment by PerilousApricot** [comment]
(I opened this to remind myself to fix this, please assign it to me)

**Comment by belforte** [comment]
Andrew, is this for you ? or for me ? And is it in Crab2 or ProdCommon ?

**Comment by PerilousApricot** [comment]
blargh, it might actually be ProdCommon. I need to hunt it down. The XML file ends up in the right place, it's just the stdout/err that end up going crazy

**Comment by belforte** [comment]
released in 2_10_4_patch2
