### ISSUE TITLE
trap all local batch interrrupts

### ISSUE THREAD

**Issue by belforte** [dmwm/CRAB2#1069]
currently crab wrapper only traps SIGUSR2 and SIGTERM
but some batch system may also send SIGINT and others
in particular CERN is 'famous' for sending SIGING
see
http://information-technology.web.cern.ch/services/fe/lxbatch/howto/how-interpet-batch-job-return-codes
also try to print in the stdout which interrupt signal was received

**Comment by belforte** [comment]
ref:
https://github.com/belforte/CRAB2/blob/master/python/crab_template.sh#L138

**Comment by PerilousApricot** [comment]
What a mess.

**Comment by belforte** [comment]
@PerilousApricot  why ? I thought this to be simple, I forgot one signal and will add, tacking the chance to flag which signal was received. But maybe I  am missing something

**Comment by PerilousApricot** [comment]
It would be nice if the batch scheduler sent the message to the wrapper
script itself instead of one of its subprocesses.

**Comment by belforte** [comment]
maybe it does, but since crab does not trap it, the message gets passed down the chain. OTH.. what do I know of how these things really work ?

**Comment by belforte** [comment]
fix released in 2_10_4_patch4
