### ISSUE TITLE
prevent users from staging out to T1_US_FNAL

### ISSUE THREAD

**Issue by belforte** [dmwm/CRAB2#1089]
Upon request from FNAL admins:

avoid that users put T1_US_FNAL as storage SE when they really needed to use T3_US_FNALLPC. There is no valid use case for T1_US_FNAL iin Crab, so if found.. throw an error and stop.

**Comment by ericvaandering** [comment]
Thanks! Maybe next week at OSG All Hands

**Comment by belforte** [comment]
if it gets urgent and you do not get to it, let me know and I should be able to push it in quickly with next patch

**Comment by belforte** [comment]
@ericvaandering  is this still needed ?

**Comment by ericvaandering** [comment]
Yes

**Comment by belforte** [comment]
seems users learnt by now
