### ISSUE TITLE
check_HN_name.py not working on SL6

### ISSUE THREAD

**Issue by chwissing** [dmwm/CRAB2#1102]
Some hack is required to make check_HN_name.py also working on SL6. Some additional command line options are required. It should work like this:

curl -s -S  --capath $X509_CERT_DIR --cacert $X509_USER_PROXY --cert $X509_USER_PROXY --key $X509_USER_PROXY 'https://cmsweb.cern.ch/sitedb/data/prod/whoami'

Note however that the variables X509_CER_DIR and X509_USER_PROXY are not set by default on SL6  lxplus.cern.ch.

Christoph

**Comment by belforte** [comment]
the lack of  X509_USER_PROXY is particularly annoying, may affect DBS3 data discovery. I thought I read that EMI developers acknowledged a regression and were going to add it back, but if it is still nothere with latest voms-proxy-init.. I guess I'll need to set it inside Crab2

**Comment by chwissing** [comment]
X509_USER_PROXY is the "usual gLite/EMI" default: /tmp/x509up_u{$ID}. X509_CERT_DIR is also the default /etc/grid-security/certificates/
You might want to use those in case they are not set in the environment.

**Comment by belforte** [comment]
yeah I know. I would probably rather use
export X509_USER_PROXY=`voms-proxy-info -path`
X509_CERT_DIR is more annoying since a site may decide to put those in some odd place, but hopefully will define the env. var. in that case.

**Comment by belforte** [comment]
take this chance to remove check with SiteDB v1 API, which have been retired
