### ISSUE TITLE
SGE submission and username

### ISSUE THREAD

**Issue by fhoehle** [dmwm/CRAB2#1107]
Dear CRAB team,

I encountered some stageout problems while using the sge scheduler. 
The LFNBaseName is created by using the  getUserName function in crab_util.py. At the NAF the local username is not equal to the username in siteDB. Therefore the stageout to a given Tier 2 fails, because LFNBaseName points to an incorrect username i.e. /store/user/<not sitedb username>/... . 
This commit:
https://github.com/fhoehle/CRAB2/commit/b265aa308dd1598310b6aed5c240c26c5d5584c0
fixes the problem by removing the whoami lookup for the SGE scheduler.
If you like I could create a pull request.

Regards,

Felix

**Comment by belforte** [comment]
Yes, this way it is better, I'll put it in. Thanks
