### ISSUE TITLE
Boss generates spurious error message if Glite is not installed

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#1132]
This line:

https://github.com/dmwm/CRAB2/blob/79eae4fd9beaa651ab25e7be909aa14a6c860deb/python/Boss.py#L42

causes an execution of the function for all schedulers whether Glite is used/called for or not. That function prints an error message to the screen if GLite is not found.

https://github.com/dmwm/CRAB2/blob/56fb88a74eb1d8a960c7642da35114ad8dacd189/python/crab_util.py#L800

You could just make this fail. Or not worry about it, it's another line in 10s that CRAB spits out to the user.

**Comment by belforte** [comment]
thanks for pinpointing the origin of the annoying message. I always wanted to get rid of it, but did not find the stamina to look for it.
I will simply remove the printout.
