### ISSUE TITLE
Migrate FE certs away from DOEGrid

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#177]
Original Savannah ticket 39757 reported by jletts on Wed Feb  6 17:12:33 2013.
1. Migrate Frontend glideinWMS certs for CMS analysis away from DOEGrid to another CA (CERN? OSG?)
2. Improve error handling for proxy renewal on Frontend.

**Comment by ericvaandering** [comment]
Comment by jletts on Mon Mar 25 05:57:27 2013

Verified that all certificates are good until at least June 4th, and the first 10 until Nov. 16th.

**Comment by ericvaandering** [comment]
Comment by jletts on Mon Apr  1 17:22:42 2013

All are good until November, just need to be copied from glidein-factory.t2.ucsd.edu.

**Comment by belforte** [comment]
On 12/10/2013 11:33 AM, letts wrote: > We have to do this by March ...

**Comment by belforte** [comment]
@jamesletts James, I think this is done. May I close ?

**Comment by jamesletts** [comment]
Yes please close this.

James
