### ISSUE TITLE
Move User Priority monitoring web pages to a more permanent home

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#178]
Original Savannah ticket 39874 reported by jletts on Fri Feb  8 12:59:18 2013.

Move User Priority web page to a more permanent home.

http://submit-3.t2.ucsd.edu/CSstoragePath/UserPrio/UserPrio-dev.html

**Comment by ericvaandering** [comment]
Comment by jletts on Mon Sep 30 14:31:24 2013

General agreement in the glideinWMS chat meeting on September 26 that this would be best moved to the Dashboard (like SSB) eventually. This means we would need some support from CompOps - unfortunately the person who currently does this work is no longer available.

**Comment by belforte** [comment]
Lola is working on the SSB part. but that will not fully replace.

**Comment by belforte** [comment]
James is re-working it anyhow
