### ISSUE TITLE
test crab with the DBS api 2_1_x to avoid problems with import of parent dataset

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#688]
Original Savannah ticket 80891 reported by fanzago on Tue Apr 12 10:54:08 2011.

The publication problem about the import of parent in some &quot;special&quot; cases ( https://savannah.cern.ch/support/?120300 and https://hypernews.cern.ch/HyperNews/CMS/get/crabFeedback/4547/1.html ) is fixed in the DBS_2_1_x api. It could be usefull to test these api with crab in order to understand if there are any show-stoppers.
To be done after the release 2_7_8

**Comment by belforte** [comment]
not needed. WE move to DBS3 on Feb 10
