### ISSUE TITLE
in the SE stageout dir contains &quot;error&quot; in the name, the checkRemoteDir fails ...

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#736]
Original Savannah ticket 88421 reported by fanzago on Wed Nov  2 13:13:58 2011.

There is a bug related to the simpleOutputCheck function of ProtocolLcgUtils. The grep about possible lcg messages includes also:

elif line.find(&quot;no such file or directory&quot;) != -1 or line.find(&quot;error&quot;) != -1 or line.find(&quot;Failed&quot;) != -1 or ....

and it raises an crab error message if the stageout remote dir contains &quot;error&quot; string in the name.

**Comment by ericvaandering** [comment]
Comment by fanzago on Thu Nov  3 10:35:36 2011

Same check is done after the copy of output file, so if the name of the output file contains the &quot;error&quot; string, the result of the check, that is a grep on the command output messages returns  copy failure, even if the copy is ok.

**Comment by belforte** [comment]
realistically, it only gave problems once, so let's live with it.
