### ISSUE TITLE
crab client gets stuck when run range is too large

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#785]
Original Savannah ticket 95734 reported by belforte on Wed Jun 27 14:26:39 2012.

see
https://hypernews.cern.ch/HyperNews/CMS/get/crabFeedback/5805/1/1/1/1/1/1.html
namely:
Since this concerns a Run2012B data set I wanted to process run 193752 and up. Naively expecting that the runselection numbers are only used as greater-than/less-than clauses somewhere I simply plugged in a huge integer as upper limit for CMSSW.runselection. This confused CRAB or DBS/DAS.

**Comment by ericvaandering** [comment]
Comment by belforte on Thu Sep 12 08:31:43 2013

it is due to
/afs/cern.ch/cms/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_3_1/python/FWCore/PythonUtilities/LumiList.py
called by crab's DataDiscovery.py
where the runselection range is turned into a list of all possible run numbers in that range
runselection = parseRange2(self.cfg_params['CMSSW.runselection'])

in LumiList a structure is prepared for all runs in the list, and if maxrun is e.g. 10^9 cpu and ram explodes, guess code starts swapping.

In my test 10^6 seems as high as one can go.
Currently we have run# around 200K, so it is something for after LS1 and I will let Cr4ab3 worry about it.

Will put a check in DataDiscovery.py to avoid it happens again

**Comment by ericvaandering** [comment]
Comment by belforte on Thu Sep 12 08:45:35 2013

done
/local/reps/CMSSW/COMP/CRAB/python/DataDiscovery.py,v  &lt;--  DataDiscovery.py
new revision: 1.50; previous revision: 1.49

**Comment by belforte** [comment]
fix released in CRAB_2_9_1
