### ISSUE TITLE
add to crab -report the lumimask of missing data

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#788]
Original Savannah ticket 95967 reported by fanzago on Tue Jul 10 10:49:31 2012.

It could be useful in the crab -report file
to add the production of the lumimask file (json) of not analyzed data, due to job failures or other reasons.
If in the crab.cfg file a lumimask is used, in the report we want to produce the lumimask file of data analyzed by the task and the lumimask of missing one as difference from the initial lumimask.
If a lumimask is not added to the crab config file, the difference could be calculated starting from the complete lumisection of the complete dataset.

**Comment by ericvaandering** [comment]
Comment by fanzago on Wed Sep  5 11:03:55 2012

In cvs the Reporter.py.

If the lumimask isn't used, I calculate the difference between the run:lumi in the argument.xml file and the analyzed in the task

**Comment by ericvaandering** [comment]
Comment by belforte on Tue Oct 23 09:49:51 2012

released in CRAB 2_8_3

**Comment by ericvaandering** [comment]
Closed by belforte on Tue Oct 23 09:49:51 2012

**Comment by belforte** [comment]
I think the implementation was plainly wrong. Given that the list of lumi's to be processed is in arguments.xml which is created at crab -create time, and so it already takes into account possible input lumimask, runselection etc. and covers the full dataset, there is no need to discriminate in the code according to CMSSW.lumi_mask, simply make the difference of lumis in arguments.xml and lumiSummary.json

**Comment by fanzago** [comment]
The arguments.xml doesn't cover the complete dataset in the case a subset of lumis was selected using the CMSSW.total_number_of_lumis not -1

**Comment by belforte** [comment]
Yes, and that's OK.
The aim of the file created by crab -report is to rescue
the lumis that this task was supposed to process and did not.
Not to extend to the full dataset beyond the initial
intention of the user.
It is possible that initial posting in Savannah by Eric
was not clear enough and misled the intial implementation.

**Comment by belforte** [comment]
see also comments to https://github.com/dmwm/CRAB2/issues/932

**Comment by fanzago** [comment]
yes, and about this point there was my last implementation described in the ticket https://github.com/dmwm/CRAB2/issues/932. So now we have a json file about the missing lumi of the user task (difference with the argument.xml) and also a file about the missing lumi related the initial lumimask provided by user.

**Comment by belforte** [comment]
fix released in 2_10_1
