### ISSUE TITLE
For remoteGlidein, some sane Hold defaults

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#832]
Original Savannah ticket 98450 reported by belforte on Thu Oct 25 08:29:20 2012.

By default, remoteGlidein will allow a job be on hold for 8 days before failure.

Sometimes the hold reason is transient and not the fault of the user.  CRAB and Dashboard doesn't appear to handle these well, so we might as well aggressive kill them.

I propose having a far shorter time between hold and removal, as well as retry jobs which went on hold for &quot;normal&quot; reasons.

See attached patch.  I also limit the number of times we can allow the job to be retried, just in case it is the fault of the user.

**Comment by ericvaandering** [comment]
Comment by belforte on Thu Oct 25 08:43:54 2012

fine of coure, but...
how do we separare responsibilitied and control between submitter (crab in this case) and frontend ?
I thought that also frontend adds conditions on when jobs are held/release/removed
Could they conflict ? who wins ?
And mostly, where do we want to have this kind of control ?

I add james and igor to the thread.

stefano

**Comment by ericvaandering** [comment]
Comment by bbockelm on Thu Oct 25 12:32:08 2012

Hi,

There's a very good motivation for putting it in the schedd - we can update schedd policies more quickly than we can update the CRAB code.

However, it would apply to everything which uses the schedd.  To have different policies for different submitters would make things get complex.

Both can be in place - if either the SYSTEM_PERIODIC_RELEASE (for all jobs in the schedd) or the PeriodicRelease in the job are true, the job is released.  Similarly for remove - if either are true, then the job is removed.

Anyhow, one way or the other, user jobs appear to stay permanently in the &quot;running&quot; state when they are put on hold (well, I only waited overnight).

Brian

**Comment by ericvaandering** [comment]
Comment by sfiligoi on Thu Oct 25 14:11:08 2012

Yes, we should have the removes and releases defined in the system config.

As for &quot;different policies for different submitters&quot; it is indeed high time to standardize what a &quot;CMS submitter&quot; looks like.

We can discuss offline how to get there.

Igor

**Comment by ericvaandering** [comment]
Comment by belforte on Thu Oct 25 14:28:31 2012

let's not get heated up.
I do not hope &quot;CMS&quot; can standardize anything.
But am all for putting in the common place things that are common.
So can we start with putting in the FE the expression Brian indicates. From what I understand by reading seems very good to me.
Once we see different users with different needs, we'll see.
I guess we need a way for a user to add some custom JDL lines anyhow, like for gLite, may even be that current crab2 works
already for that.

What I rather really want is that things like this are clearly documented and clearly controlled by CMS ops. Such configs should be in our CVS, like we used to do with CrabServer.

E.g., should be done in such a way that Stefano and Lola can change it. Not something that only Igor and/or James know how to do.

Question: do we care to know how often jobs will be resubmitted (and where) for failing the problems indicated ? IIUC those jobs restart with same condor_id, so dashboard will entries will be overwritten and will appear as a single job there.

Being able to notice and address problems is one of the reasons why we did not enable automatic resubmission in gLite WMS e.g.

**Comment by ericvaandering** [comment]
Comment by belforte on Thu Nov  8 10:29:45 2012

the more I think about this, the less I like to do this.
we should have a chat, but need to have a clear problem to solve, since to do this properly requires in the end to change the definition of jon Running, Aborted, Done.... and doing that w/o a Crab2-server-like-or-worse mess requires care.

so I am for postponing any action.

stefano

**Comment by ericvaandering** [comment]
Comment by bbockelm on Thu Nov  8 18:27:06 2012

Hi Stefano,

I think it _is_ critical.  There are 185 jobs right now which will be stuck in &quot;running&quot; state for a week prior to actually telling the user there has been an unrecoverable error.

Such is a horrible user experience!  Even if you don't restart, you should abort them immediately.

Brian

**Comment by belforte** [comment]
Crab3 will do this, not Crab2
