### ISSUE TITLE
limit publication data set name length to 200bytes

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#837]
Original Savannah ticket 98762 reported by fanzago on Mon Nov 12 02:06:50 2012.

Hi again,

it is actually a file system limitation. We are using ext3 on that partition, which has a file name length limitation of 255 bytes. Unfortunately, that means we cannot provide any workarounds. I am sorry. However, maybe you can re-publish the dataset with a shorter name (~100 bytes). 

@Stefano: 
The file name is SR-CMSSW_4_2_9_HLT1-PYTHIA6_exclLambdaBtoJpsiMuMu_7TeV_cff_py_GEN_SIM_DIGI_L1_DIGI2RAW_g0034_bunch08-StoreResults-PYTHIA6_exclLambdaBtoJpsiMuMu_7TeV_cff_py_GEN_SIM_DIGI_L1_DIGI2RAW_root_HLT_RAW2DIGI_L1Reco_RECO_g0034_b08_g0059-0e73acfc91487533b1986a056b175ad1.xml, which has 264 bytes. The publish_name Frank used has 113 bytes, so a limitation to 100 bytes would be sufficient, since the name repeated in the primary ds name. Do think that is applicable?

Cheers,
Manuel

&gt; Hi Ale, Stefano,
&gt;
&gt; let me explain what happens. The ProdAgent, which is used for StoreResult is writing a workflow description file to disk. This file is read back to ProdAgent using the python open call. Unfortunately, it is not working with paths having more than 255 characters. Unfortunately, there is no way to rename the dataset before the elevation. However, I will try to shorten the path, so that it fits the 255 character limitation, but I cannot promise to find a solution. I will let you know.
&gt;
&gt; @Stefano: I will check what's the maximum length we can handle and let you know. I would be great to have some sort of limitation already in the CRAB step. Would it be possible to not repeat the publish_data_name in the primary_ds, that would increase the maximum number characters, which can be used.
&gt;
&gt; Cheers,
&gt; Manuel
&gt;
&gt;&gt; Dear Manuel and Thomas,
&gt;&gt;
&gt;&gt; In CRAB the user is asked to configure a subset of the dataset name's string (via the publish_data_name option).
&gt;&gt; In the example below I guess Frank has used, in the generation step:
&gt;&gt; publish_data_name=PYTHIA6_exclLambdaBtoJpsiMuMu_7TeV_cff_py_GEN_SIM_DIGI_L1_DIGI2RAW_g0034_bunch04
&gt;&gt; and in the reco step:
&gt;&gt; publish_data_name=PYTHIA6_exclLambdaBtoJpsiMuMu_7TeV_cff_py_GEN_SIM_DIGI_L1_DIGI2RAW_root_HLT_RAW2DIGI_L1Reco_RECO_g0034_b04_g0059
&gt;&gt;
&gt;&gt; For sure it was possible to make them shorter, i.e. removing _cff_py_GEN_SIM_DIGI_L1_DIGI2RAW_..... or making it shorter like GENSIMRAW and RECO,  no need to repeat the PYTHIA6_exclLambdaBtoJpsiMuMu_7TeV_cff_py in name provided in the reco step.
&gt;&gt;
&gt;&gt; At this point is there some manual trick that could be applied to rename the dataset before feeding it to StoreResults?
&gt;&gt; Or the same issue will shows up with the lengthy LFN ?
&gt;&gt; thanks
&gt;&gt; Ale
&gt;&gt;
&gt;&gt;
&gt;&gt;
&gt;&gt; Il 08/11/2012 10.38, Thomas Kress ha scritto:
&gt;&gt;&gt; Dear b physics group,
&gt;&gt;&gt;
&gt;&gt;&gt; it seems that the ProdAgent (legacy) system we are still using for the StoreResults dataset elevation can not handle all of the recent b physics group requests since the dataset name is too long, e.g.
&gt;&gt;&gt; /PYTHIA6_exclLambdaBtoJpsiMuMu_7TeV_cff_py_GEN_SIM_DIGI_L1_DIGI2RAW_g0034_bunch04/frmeier-PYTHIA6_exclLambdaBtoJpsiMuMu_7TeV_cff_py_GEN_SIM_DIGI_L1_DIGI2RAW_root_HLT_RAW2DIGI_L1Reco_RECO_g0034_b04_g0059-0e73acfc91487533b1986a056b175ad1/USER
&gt;&gt;&gt;
&gt;&gt;&gt; (adding Stefano)
&gt;&gt;&gt; It the mechanism to produce such data names for these group samples unavoidable ? It contains duplicated information. Did this happen automatically by using Crab in the proposed way ?
&gt;&gt;&gt; Other groups' StoreResults requests usually do not have such long dataset names.
&gt;&gt;&gt;
&gt;&gt;&gt;     Greetings, Manuel &amp; Thomas. 
&gt;&gt;&gt;
&gt;&gt;&gt; --
&gt;&gt;&gt;              Mit besten Grüßen/With kind regards,
&gt;&gt;&gt;
&gt;&gt;&gt; Thomas Kreß, RWTH Aachen, III. Physikalisches Institut, Lehrstuhl B
&gt;&gt;&gt; Office:  28A-206, Phone:  +49 241 80 27281, Fax:  +49 241 80 22244
&gt;&gt;&gt; Email: Thomas.Kress@physik.rwth-aachen.de ; Thomas.Kress@cern.ch
&gt;&gt;&gt;            Signed with a certificate issued by GridKa-CA (GermanGrid)
&gt;&gt;&gt;
&gt;&gt;&gt;
&gt;&gt;&gt;
&gt;&gt;&gt;
&gt;&gt;&gt;
&gt;&gt;&gt;
&gt;&gt;&gt;
&gt;&gt;&gt;
&gt;&gt;&gt;
&gt;&gt;
&gt;

**Comment by ericvaandering** [comment]
Comment by fanzago on Fri Apr  5 05:28:28 2013

Hi,
in crab the user dataset name is composed by

/primaryDataset/username_publishDatasetName_psethash/USER

the limitations already implemented are related to the primaryDataset, it has to be &lt; 100 bytes and the complete LFN of file to publish that has to be &lt; 500 bytes.

I can add a check about the publishDatasetName (string written by the user in the crab.cfg), but you need the limitation to 100 bytes to the publicationDatasetName string or to the complete username_publishDatasetName_psethash? Is better to put a limitation about the complete user datasetname?

Cheers
   Federica

**Comment by ericvaandering** [comment]
Comment by belforte on Fri Apr  5 06:34:02 2013

I added Manuel Giffels in CC, since he's the one to answer

**Comment by belforte** [comment]
as discussed with Yuyi:
processed dataset name has to be < 200 chars
pset name has to be < 100 chars

The parameter set name column is defined as 1000 characters in DBS2, it is 100 in DBS3.  Processed DS name is defined as 500 characters in DBS2, 200 in DBS3.

**Comment by belforte** [comment]
this is now in WMCore/Lexicon.py
https://github.com/dmwm/WMCore/issues/4941
https://github.com/dmwm/WMCore/commit/331a44d927154d8d28b2cadc5ff49ab976764180
https://github.com/dmwm/WMCore/pull/4943
