### ISSUE TITLE
uploadLog reports error for remoteGlidein

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#860]
Original Savannah ticket 99683 reported by belforte on Mon Jan  7 09:45:25 2013.

or at least for that.

&gt;
&gt; http://cmsdoc.cern.ch:80/cms/LCG/crab/config/server_submit-2.t2.ucsd.edu.conf&lt;http://cmsdoc.cern.ch:80/cms/LCG/crab/config/server_submit-2.t2.ucsd.edu.confis&amp;gt;
&gt; is unavailable - it returned 404 because Not Found
&gt;
harmless.
But it seems there's a typo somewhere since the right link should be
http://cmsdoc.cern.ch:80/cms/LCG/crab/config/server_ucsd_submit-2.conf

**Comment by ericvaandering** [comment]
Comment by belforte on Thu Sep 12 07:51:19 2013

fixed
/local/reps/CMSSW/COMP/CRAB/python/ReportUploader.py,v  &lt;--  ReportUploader.py
new revision: 1.8; previous revision: 1.7

**Comment by belforte** [comment]
fix released in CRAB_2_9_1
