### ISSUE TITLE
put site name in JDL for glidein

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#882]
Original Savannah ticket 100339 reported by belforte on Fri Feb  8 10:44:41 2013.

e.g. when user puts it in white list, no reason to xlate into SE. since glidein matches on site name already.

**Comment by ericvaandering** [comment]
Comment by belforte on Sat Feb  9 10:48:37 2013

syntax from Igor:

On 02/09/2013 06:00 AM, Stefano Belforte wrote:
&gt; quale e' la sintassi per indicare un sito nel JDL ?
&gt; una cosa tipo
&gt; +DESIRED_SITE='T2_IT_Bari'
&gt; ?
DESIRED_Sites
http://www.slideshare.net/igor_sfiligoi/user-training-2012-matchmaking-in-glideinwms-in-cms
(slide 16)

&gt;
&gt; prende anche una lista ?
Si, come DESIRED_SES

&gt; wild chars ?
Non al momento.

Igor

**Comment by ericvaandering** [comment]
Comment by belforte on Thu Sep 12 07:56:34 2013

there is no way to go from SE to site name with the current T1**DISK thing, need to wait until we use directly phedex buffer from the start

**Comment by belforte** [comment]
implemented with  https://github.com/belforte/CRAB2/commit/2dcd5538e478e94b5fb811ec7e34c5deb73a6e2b#diff-d41d8cd98f00b204e9800998ecf8427e
