### ISSUE TITLE
make sure BossLite/SchedulerRemoteglidein never puts '' as exit code

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#884]
Original Savannah ticket 100370 reported by belforte on Mon Feb 11 07:22:09 2013.

see
https://hypernews.cern.ch/HyperNews/CMS/get/crabFeedback/6545/1/1/1/1/1/1/1.html

**Comment by ericvaandering** [comment]
Comment by belforte on Thu Sep 12 08:51:01 2013

bah.. seems something that will never happen again, let's try to ignore this.

**Comment by belforte** [comment]
wan't do --> close
