### ISSUE TITLE
crab -uploadLog ignores outputdir option in crab.cfg

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#886]
Original Savannah ticket 100818 reported by belforte on Mon Mar 11 08:41:17 2013.

uploadLog always look for stdout in ../res, even if it could be redirected using logdir option
see
https://hypernews.cern.ch/HyperNews/CMS/get/crabFeedback/6609/1/1/2/1/1/1/1/1/1/1.html

**Comment by ericvaandering** [comment]
Comment by belforte on Thu Sep 12 08:04:00 2013

should only make sure there's a decent message

**Comment by ericvaandering** [comment]
Comment by belforte on Thu Sep 12 08:12:05 2013

actually is outputdir option
changed title.
after quick look at code seems way too complex to be worth

**Comment by belforte** [comment]
won-t do --> close
