### ISSUE TITLE
crab -report dies if crab -status fails

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#899]
Original Savannah ticket 101144 reported by belforte on Tue Apr  9 10:35:26 2013.

but crab -report does not need info from remote jobs, should only work on local info. Should look into catching exception and going on.
See
https://hypernews.cern.ch/HyperNews/CMS/get/crabFeedback/6665/1/1/1/1/1/1/1/1.html

**Comment by ericvaandering** [comment]
Comment by belforte on Thu Sep 12 08:53:32 2013

realistically.. will not fix this.

**Comment by belforte** [comment]
serendiptiously found the solution, simply remove in Rerporter.py code attached to this comment:
        # TEMPORARY by Fabio, to be removed
