### ISSUE TITLE
wrong T1 site reported at creation time

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#913]
Original Savannah ticket 102200 reported by belforte on Wed Aug  7 02:41:36 2013.

e.g.
Block     1: jobs                 1-10: sites: T1_UK_RAL_MSS, T1_UK_RAL_MSS
while one should be T1_UK_RAL_Disk which has a different SE name. Suspect something in the way SE to Site is done by e.g. only using first part of site name.
Best would be to get rid of SE names and join with 
https://savannah.cern.ch/bugs/?100339
But have to see how much work it is.

**Comment by ericvaandering** [comment]
Comment by belforte on Wed Aug  7 13:55:41 2013

this is ultimately due the fact that Crab is using SiteDB.
In SiteDB currently the internal site name (RAL) is used as key and from it pend on one site the list of SE names, from the other the list of PhEDEx Nodes, so SE-to-CMSname becomes a many-to-many
that can not be resolved in not ambiguous way.
Of course for T2's so far there was always only one internal site name, only one SE and only one PhEDEx buffer, so we never noticed.

I think this can only be fixed by switching to fully and completely using PhEDEx nodes only. Which is quite some work.

Difficult to say if that is needed or not at this point.
It all depends on expected Crab2 lifetime.

**Comment by belforte** [comment]
implemented with https://github.com/belforte/CRAB2/commit/2dcd5538e478e94b5fb811ec7e34c5deb73a6e2b#diff-d41d8cd98f00b204e9800998ecf8427e
