### ISSUE TITLE
when looking for cmsRun segfault also grep for &quot;segmentation violation&quot;

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#917]
Original Savannah ticket 102368 reported by belforte on Mon Aug 26 07:14:48 2013.

at least with CMSSW_5_3_9 message is
%MSG-e FatalSystemSignal:  
A fatal system signal has occurred: segmentation violation
%MSG

**Comment by ericvaandering** [comment]
Comment by belforte on Mon Aug 26 07:15:46 2013

fixed
/local/reps/CMSSW/COMP/CRAB/python/crab_template.sh,v  &lt;--  crab_template.sh
new revision: 1.115; previous revision: 1.114

**Comment by belforte** [comment]
released in CRAB_2_9_1
