### ISSUE TITLE
T1's are not blacklisted any more when using split by lumi

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#918]
Original Savannah ticket 102400 reported by belforte on Thu Aug 29 02:31:48 2013.

while they are when using split by event :-(

things work (no job created) if using split by event, which is what I have in my
standard test config.
So there's an annoying bug, where the annoying part refers to
se b/w lista being handled differently in Crab2
for split by lumi and split by event, date since before &quot;my time&quot;.

I will try to fix this.
THere will be a crab_2_9_0_patch1

Stefano

On 08/28/2013 12:09 PM, Federica fanzago wrote:
&gt; HI all,
&gt; I'm finding a problem with the se_black_list.
&gt; I have created a task using the dataset
&gt;
&gt; /ZEE_TuneZ2star_14TeV_Eta4-pythia6/Summer13-UpgradePhase1Age0DES_DR61SLHCx_PU140Bx25_DES17_61_V5-v1/GEN-SIM-RECO
&gt;
&gt;
&gt; that is stored at
&gt;
&gt; T1_US_FNAL_MSS
&gt; T1_US_FNAL_Buffer
&gt;
&gt; in the creation message I see
&gt; crab:  SE black list applied to data location: ['T1_DE', 'T1_ES', 'T1_FR', 'T1_IT', 'T1_TW',
&gt; 'T1_US', 'T3_US_Vanderbilt_EC2']
&gt;
&gt; so I'm expected jobs will not be created
&gt; I know now jobs can run also in T1 site where disk is available, but ..is it the case?
&gt;
&gt; In the log I find
&gt; crab:  Converted blacklist: cmssrm.fnal.gov, storm-fe-cms.cr.cnaf.infn.it, cmssrmdisk.fnal.gov,
&gt; srmcms.pic.es, ccsrm.in2p3.fr, cmssrm-fzk.gridka.de, se2.accre.vanderbilt.edu, srm2.grid.sinica.edu.tw
&gt;
&gt; and then
&gt;
&gt; crab:  Job  1  Arguments:
&gt; 1/store/mc/Summer13/ZEE_TuneZ2star_14TeV_Eta4-pythia6/GEN-SIM-RECO/UpgradePhase1Age0DES_DR61SLHCx_PU140Bx25_DES17_61_V5-v1/10000/D4155DC9-26E4-E211-88A1-00248C55CC7F.root,/store/mc/Summer13/ZEE_TuneZ2star_14TeV_Eta4-pythia6/GEN-SIM-RECO/UpgradePhase1Age0DES_DR61SLHCx_PU140Bx25_DES17_61_V5-v1/10000/AE95D04B-13E4-E211-BCDE-003048678F8A.root,/store/mc/Summer13/ZEE_TuneZ2star_14TeV_Eta4-pythia6/GEN-SIM-RECO/UpgradePhase1Age0DES_DR61SLHCx_PU140Bx25_DES17_61_V5-v1/10000/52976F61-4AE4-E211-84D3-00304867C1BC.root
&gt; -1 0 1:1-1:3,1:96,1:200,1:380
&gt; /ZEE_TuneZ2star_14TeV_Eta4-pythia6/Summer13-UpgradePhase1Age0DES_DR61SLHCx_PU140Bx25_DES17_61_V5-v1/GEN-SIM-RECO#365477dc-e408-11e2-b4e6-00221959e72f
&gt;
&gt;
&gt;          Destination: ['cmssrm.fnal.gov']    CMSDestination: ['cmssrm.fnal.gov']   &lt;---------------
&gt;
&gt;
&gt; crab:  Creating 167 jobs, please wait...
&gt; crab:  Creation Time: 4.42675590515
&gt; crab:  Total of 167 jobs created.
&gt;
&gt;
&gt; and the task is also submitted.
&gt;
&gt;
&gt; Cheers
&gt;      Federica

**Comment by ericvaandering** [comment]
Comment by belforte on Fri Aug 30 11:37:08 2013

also split by event seems not to work as expected.
I need to fully review all this mess.

**Comment by ericvaandering** [comment]
Comment by belforte on Thu Sep  5 09:43:17 2013

tentatively fixed
/local/reps/CMSSW/COMP/CRAB/python/Splitter.py,v  &lt;--  Splitter.py
new revision: 1.61; previous revision: 1.60

extensive testing is needed, since there are so many possibilities

**Comment by belforte** [comment]
fix released in CRAB_2_9_1
