### ISSUE TITLE
remoteGlidein to pick exit code fom classAd, not fjr

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#920]
Original Savannah ticket 102413 reported by belforte on Thu Aug 29 09:41:02 2013.

retrieve exit code from condor_history no need to grep fjr.
For this to be possible condor must allow the job to publish one class ad. Tracked in this condor ticket:
https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=3353

**Comment by belforte** [comment]
guess I am leaving this for Crab3 at this point
