### ISSUE TITLE
in 290 override_data_location does not work

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#921]
Original Savannah ticket 102436 reported by belforte on Sat Aug 31 16:01:27 2013.

list of desired SE&quot;s is printed as unicode instead of string,
likely another effect of SiteDB V2 API

DESIRED_SEs = &quot; u'se1.accre.vanderbilt.edu', u'srm.ihepa.ufl.edu', u'cmssrm.hep.wisc.edu', u'bsrm-1.t2.ucsd.edu', u'srm-dcache.rcac.purdue.edu', u'srm.unl.edu', u'red-srm1.unl.edu', u'bsrm-3.t2.ucsd.edu', u'se3.accre.vanderbilt.edu', u'se01.cmsaf.mit.edu', u'dcache07.unl.edu', u'cit-se.ultralight.org',u'srmb.ihepa.ufl.edu'&quot;

**Comment by ericvaandering** [comment]
Comment by belforte on Mon Sep  2 09:48:18 2013

indeed it is due to SiteDB V2 API returning unicode.
This particular case is fixed explicitly casting to string 

/local/reps/CMSSW/COMP/CRAB/python/cms_cmssw.py,v  &lt;--  cms_cmssw.py
new revision: 1.398; previous revision: 1.39

I will look for other cases

**Comment by ericvaandering** [comment]
Comment by belforte on Tue Sep  3 08:57:33 2013

found another place where unicode from SiteDB could create problems, and added explicit cast to string there as well

/local/reps/CMSSW/COMP/CRAB/python/SchedulerRemoteglidein.py,v  &lt;--  SchedulerRemoteglidein.py
new revision: 1.22; previous revision: 1.21

**Comment by belforte** [comment]
released in CRAB_2_9_1
