### ISSUE TITLE
Missing hostname in Analsysis failed jobs

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#922]
Original Savannah ticket 102452 reported by belforte on Mon Sep  2 10:01:59 2013.

Title complement : (that had time to exit properly)

Hi, 

Assigned to DashBoard as it makes sense but the issue might be more for CRAB Devs and AnaOps, full discussion :

https://hypernews.cern.ch/HyperNews/CMS/get/comp-monitoring/230/1/2/1.html

To make it short I will try to skip what I already wrote in the HN. Let me know if you want me to cp/paste here.

To speed things up I already had a look into the CRAB wrapper (CMSSW.sh) and found that in the line 501 when it declares the exit code it already prints itself the hostname, but this is never propagated up [1]

The way to get it reported should be to run this :

echo &quot;WNHostName=`hostname`&quot; | tee -a $RUNTIME_AREA/$repo

That will send the right info to: 
jobreport.txt

And the DashBoard report generator should do the right thing after this is done.

Obviously the patch will be in the script that generates the wrapper, so I'll leave for CRAB people to make/test the patch. 

If you want to test it quickly, I can &quot;not fix&quot; my site and you submit a quick task to it, asking for CMSSW_5_3_9_patch3 and we will see the difference (or not).

Thanks,
Samir

[1] :

scram project CMSSW CMSSW_5_3_8
status=$?
if [ $status != 0 ] ; then
    echo &quot;ERROR ==&gt; CMSSW CMSSW_5_3_8 not found on `hostname`&quot; 
    job_exit_code=10034
    func_exit

**Comment by ericvaandering** [comment]
Comment by belforte on Mon Sep  2 07:48:30 2013

upon close look, hostname is reported correctly e.g. for jobs that succeed, so it seems that when SCRAM fails the needed part of crab job wrapper is not executed.
Assigning to me for investigation as a crab bug.

**Comment by ericvaandering** [comment]
Comment by belforte on Mon Sep  2 10:01:59 2013

yes, it is Crab, move to Crab bug tracker

**Comment by ericvaandering** [comment]
Comment by belforte on Mon Sep  2 10:01:59 2013

This item has been reassigned from the project CMS Computing Infrastructure  Support support tracker to your tracker.

The original report is still available at support #139565

Following are the information included in the original report:
- [field #0]                  Item ID: 139565
- [field #1]                 Group ID: 452
- [field #2]              Open/Closed: Open
- [field #3]                 Severity: 3 - Normal
- [field #4]                  Privacy: Public
- [field #9]                 Category: Analysis Operations
- [field #10]             Submitted by: samircury
- [field #11]              Assigned to: belforte
- [field #12]             Submitted on: 2013-09-02 12:38
- [field #13]                  Summary: Missing hostname in Analsysis failed jobs
- [field #14]      Original Submission: Title complement : (that had time to exit properly)

Hi, 

Assigned to DashBoard as it makes sense but the issue might be more for CRAB Devs and AnaOps, full discussion :

https://hypernews.cern.ch/HyperNews/CMS/get/comp-monitoring/230/1/2/1.html

To make it short I will try to skip what I already wrote in the HN. Let me know if you want me to cp/paste here.

To speed things up I already had a look into the CRAB wrapper (CMSSW.sh) and found that in the line 501 when it declares the exit code it already prints itself the hostname, but this is never propagated up [1]

The way to get it reported should be to run this :

echo "WNHostName=`hostname`" | tee -a $RUNTIME_AREA/$repo

That will send the right info to: 
jobreport.txt

And the DashBoard report generator should do the right thing after this is done.

Obviously the patch will be in the script that generates the wrapper, so I ll leave for CRAB people to make/test the patch. 

If you want to test it quickly, I can "not fix" my site and you submit a quick task to it, asking for CMSSW_5_3_9_patch3 and we will see the difference (or not).

Thanks,
Samir

[1] :

scram project CMSSW CMSSW_5_3_8
status=$?
if [ $status != 0 ] ; then
    echo "ERROR ==> CMSSW CMSSW_5_3_8 not found on `hostname`" 
    job_exit_code=10034
    func_exit
- [field #16]               Item Group: None
- [field #17]                   Status: None
- [field #18]        Component Version: None
- [field #19]         Operating System: None
- [field #20]          Reproducibility: None
- [field #21]               Size (loc): None
- [field #22]            Fixed Release: None
- [field #23]          Planned Release: None
- [field #24]                   Effort: 0.00
- [field #28]                 Priority: 5 - Normal
- [field #31]         Percent Complete: 0%
- [field #33]                  Release: None
- [field #58]                     Site: None
- [field #59]                 Use GGUS: No
- [field #60]     Custom Select Box #3: None
- [field #61]     Custom Select Box #4: None
- [field #62]     Custom Select Box #5: None
- [field #63]     Custom Select Box #6: None
- [field #64]     Custom Select Box #7: None
- [field #65]     Custom Select Box #8: None
- [field #66]     Custom Select Box #9: None
- [field #67]    Custom Select Box #10: None

**Comment by ericvaandering** [comment]
Comment by belforte on Mon Sep  2 10:06:18 2013

changed crab wrapper to make sure WNHostName is in the first message sent to dashboard as soon as job starts.
Two one-line changes:

/local/reps/CMSSW/COMP/CRAB/python/crab_template.sh,v  &lt;--  crab_template.sh
new revision: 1.116; previous revision: 1.115

/local/reps/CMSSW/COMP/CRAB/python/SchedulerGrid.py,v  &lt;--  SchedulerGrid.py
new revision: 1.147; previous revision: 1.146

**Comment by ericvaandering** [comment]
Comment by samircury on Tue Sep  3 04:00:33 2013

Hi Stefano,

I'm surprised with something. I see now 10034 jobs reporting correctly :

http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#user=&amp;refresh=0&amp;table=JobDetailedView&amp;p=4&amp;records=25&amp;activemenu=0&amp;usr=BrianCalvert/bcalvert&amp;site=T2_US_Caltech&amp;submissiontool=&amp;application=CMSSW_5_3_9_patch3&amp;activity=&amp;status=app-failed&amp;check=terminated&amp;tier=&amp;date1=2013-9-2+8%3A14%3A56&amp;date2=2013-9-3+8%3A14%3A56&amp;sortby=application&amp;scale=linear&amp;bars=20&amp;ce=&amp;rb=&amp;grid=&amp;jobtype=&amp;submissionui=&amp;dataset=&amp;submissiontype=&amp;task=&amp;subtoolver=&amp;genactivity=analysis&amp;outputse=&amp;appexitcode=&amp;offset=0&amp;count=910&amp;exitcode=site&amp;fail=site&amp;cat=

But I was thinking that it would take users to update their own client sides for this to take effect.

Or you updated the code in the afs deployment? Anyway, is this expected somehow? Not sure if is the patch taking effect, but likely.

Thanks,
Samir

**Comment by ericvaandering** [comment]
Comment by belforte on Tue Sep  3 04:48:48 2013

I think the user did a crab -get and retrieved output file, at which time crab client updated all info to dashboard again.
The fix I have committed will make sure that WN is reported when job start running.

stefano

**Comment by belforte** [comment]
released in CRAB_2_9_1
