### ISSUE TITLE
if there's no AppExitCode JobExit code is not updated at crab -status time by remoteGlidein

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#923]
Original Savannah ticket 102455 reported by belforte on Mon Sep  2 10:20:27 2013.

i.e. from crab.log:

2013-09-02 16:03:04,844 [DEBUG]         Execute command :
gsissh -o ControlMaster=auto -o ControlPath=/tmp/belforte/.ssh/ssh-link-448078102-submit-4.t2.ucsd.edu -o BatchMode=yes -o StrictHo
stKeyChecking=no -o ForwardX11=no submit-4.t2.ucsd.edu &quot;cd belforte_crab_0_130902_155134_62zq4g; egrep -H WrapperExitCode|ExeExitC
ode crab_fjr_*xml|tr '_.\t&quot;' ' '|awk '{print \$3&quot; &quot;\$7&quot; &quot;\$9}'&quot;
2013-09-02 16:03:05,403 [DEBUG]         Status,output= 0
1 10034 WrapperExitCode
2013-09-02 16:03:06,260 [INFO]  
ID    END STATUS            ACTION       ExeExitCode JobExitCode E_HOST

---

1     N   Done              Terminated                           cit-gatekeeper.ultralight.org
2     N   Created           Created  
3     N   Created           Created                              

this is due to bad indentation in SchedulerRemoteglidein.py in BossLite, so will need a new ProdCommon tag

**Comment by ericvaandering** [comment]
Comment by belforte on Mon Sep  2 10:33:21 2013

fix tested and committed

/local/reps/CMSSW/COMP/PRODCOMMON/src/python/ProdCommon/BossLite/Scheduler/SchedulerRemoteglidein.py,v  &lt;--  SchedulerRemoteglidein.py
new revision: 1.29; previous revision: 1.28

**Comment by ericvaandering** [comment]
Comment by belforte on Mon Sep  2 10:38:43 2013

typo slipped in, new version
/local/reps/CMSSW/COMP/PRODCOMMON/src/python/ProdCommon/BossLite/Scheduler/SchedulerRemoteglidein.py,v  &lt;--  SchedulerRemoteglidein.py
new revision: 1.30; previous revision: 1.29

**Comment by ericvaandering** [comment]
Comment by belforte on Tue Sep  3 09:05:18 2013

tagged as PRODCOMMON_0_12_18_CRAB_57
and added to Crab client

/local/reps/CMSSW/COMP/CRAB/python/PrepareTarBall.sh,v  &lt;--  PrepareTarBall.sh
new revision: 1.197; previous revision: 1.196

**Comment by belforte** [comment]
fix released in CRAB_2_9_1
