### ISSUE TITLE
fix typo in SchedulerRemoteGlidein: self, not slef

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#924]
Original Savannah ticket 102476 reported by belforte on Wed Sep  4 13:25:10 2013.

see
https://hypernews.cern.ch/HyperNews/CMS/get/crabFeedback/6904/2.html

crab:  Stale ssh control socket: /tmp/rchatter/.ssh/ssh-link--1925900194-hcc-crabserver.unl.edu

crab: Unexpected exception executing Status Query operation : Traceback (most recent call last):
  File &quot;/afs/cern.ch/cms/ccs/wm/scripts/Crab/CRAB_2_9_0/python/Boss.py&quot;, line 181, in queryEverything
    statusRes =  self.schedSession().query( str(taskid))
  File &quot;/afs/cern.ch/cms/ccs/wm/scripts/Crab/CRAB_2_9_0/external/ProdCommon/BossLite/API/BossLiteAPISched.py&quot;, line 222, in query
    self.scheduler.query( task, queryType )
  File &quot;/afs/cern.ch/cms/ccs/wm/scripts/Crab/CRAB_2_9_0/external/ProdCommon/BossLite/Scheduler/Scheduler.py&quot;, line 152, in query
    self.schedObj.query( obj, self.parameters['service'], objType )
  File &quot;/afs/cern.ch/cms/ccs/wm/scripts/Crab/CRAB_2_9_0/external/ProdCommon/BossLite/Scheduler/SchedulerRemoteglidein.py&quot;, line 423, in query
    self.removeGsisshSocket()
  File &quot;/afs/cern.ch/cms/ccs/wm/scripts/Crab/CRAB_2_9_0/external/ProdCommon/BossLite/Scheduler/SchedulerRemoteglidein.py&quot;, line 917, in removeGsisshSocket
    slef.logging.info(&quot;last used on %s&quot; % lastTime)
NameError: global name 'slef' is not defined

**Comment by ericvaandering** [comment]
Comment by belforte on Thu Sep  5 07:30:40 2013

ok
/local/reps/CMSSW/COMP/PRODCOMMON/src/python/ProdCommon/BossLite/Scheduler/SchedulerRemoteglidein.py,v  &lt;--  SchedulerRemoteglidein.py
new revision: 1.31; previous revision: 1.30

**Comment by ericvaandering** [comment]
Comment by belforte on Thu Sep  5 07:34:26 2013

inserted that in tag scheduler for next crab client
 PRODCOMMON_0_12_18_CRAB_57

**Comment by belforte** [comment]
released in CRAB_2_9_1
