### ISSUE TITLE
warn that data_location_override only works in crab.cfg

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#925]
Original Savannah ticket 102488 reported by belforte on Thu Sep  5 09:12:34 2013.

not in crab -submit -GRID.data_location_override=...

**Comment by ericvaandering** [comment]
Comment by belforte on Thu Sep  5 09:14:56 2013

fixed
/local/reps/CMSSW/COMP/CRAB/python/crab_help.py,v  &lt;--  crab_help.py
new revision: 1.180; previous revision: 1.179

**Comment by belforte** [comment]
released in CRAB_2_9_1
