### ISSUE TITLE
avoid exit code = 70500 if running user script

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#928]
Original Savannah ticket 102659 reported by None on Mon Sep 23 10:35:45 2013.

when user indicates a custom script with script_exe, it may not always be possible (or useful) to produce a FJR file.
I found one user e.g. running thousands of Sherpa generation jobs, exit wws ending fine but user made no attempt to create an FJR.
We should avoid treating this as errors, so not to confuse monitoring.

**Comment by ericvaandering** [comment]
Comment by belforte on Fri Oct  4 09:42:43 2013

checked with Federica how to prevent accidental publication with incompleted fjrs. Sounds if there's no LFN in fjr we are OK. I will verify. Anyhow apprach should be not to look for fjr if user provided script_exe and did not ask for publication, but create fake one with exit code from user's exe.

**Comment by belforte** [comment]
relevant code to change is in 
https://github.com/belforte/CRAB2/blob/master/python/cms_cmssw.py#L1153

**Comment by belforte** [comment]
maybe it the fjr parsing at the end of cmsRun/script_exe that needs fixing ?

**Comment by belforte** [comment]
bah... I can't reproduce this and indeed code looks OK.
I do not see jobs failed with 70500 in last month in dashboard.
