### ISSUE TITLE
remove CMSSW version from JDL for gLite

### ISSUE THREAD

**Issue by belforte** [dmwm/CRAB2#936]
we will not publish CMSSW tags any more

**Comment by chwissing** [comment]
Hi Stefano, during the routine tests by Andrea it turned out that this was not 100% correct. I try ro submit a patch to fix it (and I am completely new to Githup as well).

**Comment by belforte** [comment]
thanks Christoph, if you tell me what the problem is can also try to fix. I only did one crab -createJdl and verified that CMSSW version was not among the requirements. Or send me the patch and I will commit. I am not sure you can commit to this repository. But have not had the patience to learn git authorization things as well.

**Comment by chwissing** [comment]
hi Stefano let me try to reply here since I failed to push back my 
changes (no ideas about Githup authorizations either....).

Find attached a patch for cms_cmssw.py, which should fix it.

I also saw that the version counter is still at 2.9.1, you might want to 
increase it to 2.9.2 in common.py.

Cheers, Christoph

**Comment by belforte** [comment]
thanks Christoph, I'll do. stefano

On 11/22/2013 12:09 PM, Christoph Wissing wrote:

> hi Stefano let me try to reply here since I failed to push back my
> changes (no ideas about Githup authorizations either....).
> 
> Find attached a patch for cms_cmssw.py, which should fix it.
> 
> I also saw that the version counter is still at 2.9.1, you might want to
> increase it to 2.9.2 in common.py.
> 
> Cheers, Christoph
> 
> On 11/22/2013 11:56 AM, belforte wrote:
> 
> > thanks Christoph, if you tell me what the problem is can also try to
> > fix. I only did one crab -createJdl and verified that CMSSW version was
> > not among the requirements. Or send me the patch and I will commit. I am
> > not sure you can commit to this repository. But have not had the
> > patience to learn git authorization things as well.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/dmwm/CRAB2/issues/936#issuecomment-29064509.
> > 
> > 1022a1023
> > 
> > ### SB & ChW remove requirement for explict CMSSW version
> > 
> > 1024c1025
> > 
> > ## < req+=' && Member("VO-cms-' + \
> > 
> > req+='Member("VO-cms-' + \
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dmwm/CRAB2/issues/936#issuecomment-29065159.

## 

Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by belforte** [comment]
took the chance to clean up a bit and make it safe against scram_arch not being defined:

**Comment by belforte** [comment]
fix released in 2_9_2
