### ISSUE TITLE
Default proxy length

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRAB2#961]
I just had a chat with Tony Tiradani. I gather that servers (e.g. DBS) that are SL6 will no longer work with 512 bit proxies. We don't have SL6 servers yet, but the solution is simple enough we may want to inoculate ourself now agains any issues. One can supply -bits 1024|2048|4096 on the command line for the voms-proxy-init command to generate a longer proxy.

1024 is the default in recent OSG clients and in the very latest (or maybe forthcoming) EMI client, but this change would allow older clients to be future proof. Maybe this is easy enough to do in 2_10?

**Comment by belforte** [comment]
easy yes, but.. is it needed ? current gLite UI 3.2.11 used e.g. at lxplus and LPC makes 1024-bit proxies already. We had not seen any hint of 512bit user's proxies around.
changing v-p-i command in crab2 requires a new tag of ProdCommon, too much work.

**Comment by ericvaandering** [comment]
Ah, then I would say "no." I had understood 512 bits were common.

**Comment by belforte** [comment]
ok, let's close.
